// INDEX.HTML
const translations = {
    es: {
        video: "VIDEOS",
        titulo: "WEB PARA TODOS",
        recursos: "RECURSOS",
        intro: "¿QUÉ ES LA ACCESIBILIDAD WEB?",
        introInfo: "La accesibilidad es el conjunto de prácticas y principios que buscan asegurar que todos puedan acceder, entender y usar un entorno, producto, servicio o contenido, independientemente de sus capacidades físicas, cognitivas o sensoriales. Se aplica a muchos ámbitos, como el diseño de espacios, tecnologías, información, y servicios.",
        consejoVisibilidad: "Visibilidad",
        infoVisibilidad: "Consejos y prácticas para personas con problemas de visibilidad.",
        saber1: "Saber más",
        consejoAudicion: "Audición",
        infoAudicion: "Consejos y prácticas para personas con problemas de audición.",
        saber2: "Saber más",
        consejoCognitivo: "Cognitivos",
        infoCognitivo: "Consejos y prácticas para personas con problemas cognitivos.",
        saber3: "Saber más",
        caracteristicas: "Características",
        infoCaracteristica: "Perceptibilidad: La información debe ser perceptible para todos los usuarios. Operabilidad: Los usuarios deben poder interactuar con el producto o servicio sin dificultades. Flexibilidad: La accesibilidad debe prever diferentes necesidades, adaptándose a los diversos modos en que los usuarios pueden interactuar con el entorno.",
        lograr: "¿Cómo se logra?",
        infoLograr: "Lograr la accesibilidad implica implementar prácticas y estrategias en el diseño y desarrollo de entornos, productos y servicios para que sean inclusivos y fáciles de usar por personas con diversas capacidades.",
        utilidad: "¿Para qué sirve?",
        infoUtilidad: "La accesibilidad sirve para garantizar que todas las personas, sin importar sus capacidades físicas, sensoriales, cognitivas o tecnológicas, puedan usar y beneficiarse de entornos, productos y servicios. Para promover la igualdad, mejorar la experiencia del usuario y aumentar el alcance y la audiencia.",
        nosotros: "Sobre nosotros",
        infoNosotros: "Somos estudiantes de la orientación de Informática del Martín Zapata...",
        redes: "Redes sociales",
        derechos: "Copyright © 2024 Todos los derechos reservados."
    },
    en: {
        saber: "Learn more",
        video: "VIDEOS",
        titulo: "WEB FOR EVERYONE",
        recursos: "RESOURCES",
        intro: "WHAT IS THE WEB ACCESSIBILITY?",
        introInfo: "Accessibility is the set of practices and principles that aim to ensure that everyone can access, understand, and use an environment, product, service, or content, regardless of their physical, cognitive, or sensory abilities. It applies to many fields, such as space design, technologies, information, and services.",
        consejoVisibilidad: "Visibility",
        infoVisibilidad: "Tips and practices for people with visibility problems.",
        saber1: "Learn more",
        consejoAudicion: "Hearing",
        infoAudicion: "Tips and practices for people with hearing problems.",
        saber2: "Learn more",
        consejoCognitivo: "Cognitive",
        infoCognitivo: "Tips and practices for people with cognitive issues.",
        saber3: "Learn more",
        caracteristicas: "Features",
        infoCaracteristica: "Perceptibility: Information must be perceptible to all users. Operability: Users must be able to interact with the product or service without difficulties. Flexibility: Accessibility should anticipate different needs, adapting to the various ways users may interact with the environment.",
        lograr: "How is it achieved?",
        infoLograr: "Achieving accessibility involves implementing practices and strategies in the design and development of environments, products, and services to make them inclusive and easy to use for people with diverse abilities.",
        utilidad: "What is it for?",
        infoUtilidad: "Accessibility ensures that all people, regardless of their physical, sensory, cognitive, or technological capabilities, can use and benefit from environments, products, and services. It promotes equality, enhances user experience, and increases reach and audience.",
        nosotros: "About us",
        infoNosotros: "We are students from the IT orientation of Martín Zapata...",
        redes: "Social networks",
        derechos: "Copyright © 2024 All rights reserved."
    },
    pt:{
        saber: "Saber mais",
        video: "VÍDEOS",
        titulo: "SITE PARA TODOS",
        recursos: "RECURSOS",
        intro: "O QUE É O ACCESIBILIDADE NA WEB?",
        introInfo: "Acessibilidade é o conjunto de práticas e princípios que buscam garantir que todos possam acessar, compreender e utilizar um ambiente, produto, serviço ou conteúdo, independentemente de suas capacidades físicas, cognitivas ou sensoriais. É aplicado em diversas áreas, como design de espaços, tecnologias, informação e serviços.",
        consejoVisibilidad: "Visibilidade",
        infoVisibilidad: "Dicas e práticas para pessoas com problemas de visibilidade.",
        saber1: "Saber mais",
        consejoAudicion: "Audição",
        infoAudicion: "Dicas e práticas para pessoas com problemas auditivos",
        saber2: "Saber mais",
        consejoCognitivo: "Cognitivo",
        infoCognitivo: "Dicas e práticas para pessoas com problemas cognitivos.",
        saber3: "Saber mais",
        caracteristicas: "Características",
        infoCaracteristica: "Perceptibilidade: A informação deve ser perceptível a todos os usuários.Operabilidade: Os usuários devem poder interagir com o produto ou serviço sem dificuldades.Flexibilidade: A acessibilidade deve antecipar diferentes necessidades, adaptando-se às diversas formas como Os usuários podem interagir com o ambiente.",
        lograr: "Como isso é alcançado?",
        infoLograr: "Alcançar a acessibilidade envolve implementar práticas e estratégias na concepção e desenvolvimento de ambientes, produtos e serviços para que sejam inclusivos e fáceis de usar por pessoas com diversas capacidades.",
        utilidad: "Para que serve?",
        infoUtilidad: "A acessibilidade serve para garantir que todas as pessoas, independentemente das suas capacidades físicas, sensoriais, cognitivas ou tecnológicas, possam utilizar e beneficiar dos ambientes, produtos e serviços. Para promover a igualdade, melhorar a experiência do usuário e aumentar o alcance e o público.",
        nosotros: "Sobre nós",
        infoNosotros: "Somos alunos da orientação Ciência da Computação de Martín Zapata...",
        redes: "Redes Sociais",
        derechos: "Copyright © 2024 Todos os direitos reservados."

    },
    ja:{
        saber: "もっと詳しく知る",
        video: "動画",
        titulo: "誰でも使えるウェブ",
        recursos:"リソース",
        intro: "とは何ですか",
        intro2: "ウェブへのアクセス?",
        introInfo: "アクセシビリティとは、身体的、認知的、感覚的能力に関係なく、誰もが環境、製品、サービス、またはコンテンツにアクセスし、理解し、使用できるようにするための一連の実践と原則です。空間デザイン、技術、情報、サービスなど幅広い分野に応用されています。",
        consejoVisibilidad: "可視性",
        infoVisibilidad: "視認性に問題がある人のためのヒントと実践。",
        saber1: "もっと詳しく知る",
        consejoAudicion: "聴覚",
        infoAudicion: "聴覚に問題がある人のためのヒントと実践。",
        saber2: "もっと詳しく知る",
        consejoCognitivo: "認知的",
        infoCognitivo: "認知機能に問題がある人のためのヒントと実践。",
        saber3: "もっと詳しく知る",
        caracteristicas: "特徴",
        infoCaracteristica: "知覚可能性: 情報はすべてのユーザーが知覚可能である必要があります。操作性: ユーザーは製品やサービスを問題なく操作できる必要があります。柔軟性: アクセシビリティは、ユーザーが環境と対話できるさまざまな方法に適応して、さまざまなニーズに対応できる必要があります。",
        lograr: "それはどのように達成されるのでしょうか?",
        infoLograr: "アクセシビリティの実現には、環境、製品、サービスが包括的で、多様な能力を持つ人々にとって使いやすいものとなるよう、環境、製品、サービスの設計と開発における実践と戦略の導入が含まれます。",
        utilidad: "それは何のためにあるのでしょうか？",
        infoUtilidad: "アクセシビリティは、身体的、感覚的、認知的、技術的能力に関係なく、すべての人々が環境、製品、サービスを利用し、恩恵を受けることができるようにするために役立ちます。平等を促進し、ユーザーエクスペリエンスを向上させ、リーチと視聴者を増加させます。",
        nosotros: "私たちについて",
        infoNosotros: "私たちはMartín Zapataのコンピュータサイエンスオリエンテーションの学生です...",
        redes: "ソーシャルネットワーク",
        derechos: "著作権 © 2024 全著作権所有。"
    }
};

function changeLanguage(lang) {
    const elements = {
        video: "video",
        titulo: "titulo",
        recursos: "recursos",
        intro: "intro",
        introInfo: "intro-info",
        consejoVisibilidad: "consejo-visibilidad",
        infoVisibilidad: "info-visibilidad",
        saber1: "saber1",
        consejoAudicion: "consejo-audicion",
        infoAudicion: "info-audicion",
        saber2: "saber2",
        consejoCognitivo: "consejo-cognitivo",
        infoCognitivo: "info-cognitivo",
        saber3: "saber3",
        caracteristicas: "caracteristicas",
        infoCaracteristica: "info-caracteristica",
        lograr: "lograr",
        infoLograr: "info-lograr",
        utilidad: "utilidad",
        infoUtilidad: "info-utilidad",
        nosotros: "nosotros",
        infoNosotros: "info-nosotros",
        redes: "redes",
        derechos: "derechos"
    };

    for (const key in elements) {
        const elementId = elements[key];
        const text = translations[lang][key];
        if (document.getElementById(elementId)) {
            document.getElementById(elementId).innerText = text;
        }
    }
}
